---
- name: "Install docker"
  block:
  - name: Copy running file to remote
    template:
      src: "/app/ansible/vps-playbook/roles/files/{{ ansible_distribution }}/install-docker.sh.j2"
      dest: "/tmp/docker-install.sh"

  - name: Install docker
    shell: bash /tmp/docker-install.sh >> /tmp/devpanel.logs

  - name: Reset ssh connection to allow user added to docker group in the docker role to take effect.
    meta: reset_connection
