---
- hosts: localhost
  connection: local
  tasks:
  - name : Init VPS Local Block
    rescue:
      - include_tasks: "tasks/dp-task-error-handler.yml"
    block:
      - name: write private key to ~/.devpanel/privKey
        copy:
          dest: ~/.devpanel/privKey
          mode: '0400'
          content: |
            {{ vps.privKey }}

      - name: Add VPS to host group
        add_host:
          hostname: "{{ vps.publicIpAddress }}"
          groups: vps
          ansible_ssh_private_key_file: '~/.devpanel/privKey'
          ansible_host_key_checking: false
          ansible_user: "{{ vps.vpsUsername }}"

- hosts: all
  tasks:
    - name: "Install Docker"
      rescue:
        - include_tasks: "tasks/dp-task-error-handler.yml"
      block:
        - include_tasks: "./roles/tasks/install-docker.yml"
        - set_fact:
            sns_msg:
              id: "{{ actionId }}"
              status: "SUCCESS"
              payload: {}

        - name: Notify action with id {{ actionId }} is completed
          uri:
            url: "{{ callbackURL }}"
            method: "{{ callbackMethod }}"
            body_format: json
            # headers:
            #   Authorization : "Bearer {{ callbackToken }}"
            body: "{{ sns_msg | to_json }}"
          register: _result
          until: _result.status == 200
