name: Trigger pipeline to build the process
on:
  push:
    branches:
      - main
      - develop
jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up cURL
        run: sudo apt update && sudo apt install -y curl

      - name: Execute cURL command with environment variable
        run: |
          curl --fail --request POST --form token= ${{ secrets.AGENT_TRIGGER_TOKEN }} --form ref=${{ github.event.workflow_run.head_branch }} "https://gitlab.com/api/v4/projects/38531806/trigger/pipeline"
